var a=30;
var b=45;
var c= a*b;
var d=a+b;
var e=a/b;
var f=a%b;
var g=a++;
var h=a>b;
var i=a<b;
var isNum1 = a==b;
var isNum2 = a===b;
document.write("<div>c value is : "+c+"</div>");
document.write("<div>d value is : "+d+".</div>");
document.write("<div>Value of e is "+e+".</div>");
document.write("<div>Value of f is :"+f+"</div>");
document.write("<div>Value of g is :"+g+"</div>");
document.write("<div>Now Value of a is :"+a+"</div>");
document.write("<div>Value of h is :"+h+"</div>");
document.write("<div>Value of i is :"+i+"</div>");
document.write("<div>Value of isNum1 is :"+isNum1+"</div>");
document.write("<div>Value of isNum2 is :"+isNum2+"</div>");
